package com.ccdc.hrms.dao;

import com.ccdc.hrms.bean.Employee;
import com.ccdc.hrms.bean.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    int deleteByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    Employee selectByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    int updateByPrimaryKey(Employee record);
}