package com.ccdc.hrms.bean;

import java.util.Date;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.ID
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.DEPT_NAME
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.DEPT_CODE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.CREATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.CREATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.UPDATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.STATUS
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.ID
     *
     * @return the value of sys_department.ID
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.ID
     *
     * @param id the value for sys_department.ID
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.DEPT_NAME
     *
     * @return the value of sys_department.DEPT_NAME
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.DEPT_NAME
     *
     * @param deptName the value for sys_department.DEPT_NAME
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.DEPT_CODE
     *
     * @return the value of sys_department.DEPT_CODE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.DEPT_CODE
     *
     * @param deptCode the value for sys_department.DEPT_CODE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.CREATE_DATE
     *
     * @return the value of sys_department.CREATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.CREATE_DATE
     *
     * @param createDate the value for sys_department.CREATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.CREATE_USER
     *
     * @return the value of sys_department.CREATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.CREATE_USER
     *
     * @param createUser the value for sys_department.CREATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.UPDATE_DATE
     *
     * @return the value of sys_department.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.UPDATE_DATE
     *
     * @param updateDate the value for sys_department.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.UPDATE_USER
     *
     * @return the value of sys_department.UPDATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.UPDATE_USER
     *
     * @param updateUser the value for sys_department.UPDATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.STATUS
     *
     * @return the value of sys_department.STATUS
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.STATUS
     *
     * @param status the value for sys_department.STATUS
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}