package com.ccdc.hrms.bean;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.EMPLOYEE_ID
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.EMPLOY_NAME
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String employName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.GENDER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.MAIL
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.PHONE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.DEPT_CODE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.CREATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.CREATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.UPDATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.STATUS
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.EMPLOYEE_ID
     *
     * @return the value of sys_employee.EMPLOYEE_ID
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.EMPLOYEE_ID
     *
     * @param employeeId the value for sys_employee.EMPLOYEE_ID
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.EMPLOY_NAME
     *
     * @return the value of sys_employee.EMPLOY_NAME
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getEmployName() {
        return employName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.EMPLOY_NAME
     *
     * @param employName the value for sys_employee.EMPLOY_NAME
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setEmployName(String employName) {
        this.employName = employName == null ? null : employName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.GENDER
     *
     * @return the value of sys_employee.GENDER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.GENDER
     *
     * @param gender the value for sys_employee.GENDER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.MAIL
     *
     * @return the value of sys_employee.MAIL
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.MAIL
     *
     * @param mail the value for sys_employee.MAIL
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.PHONE
     *
     * @return the value of sys_employee.PHONE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.PHONE
     *
     * @param phone the value for sys_employee.PHONE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.DEPT_CODE
     *
     * @return the value of sys_employee.DEPT_CODE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.DEPT_CODE
     *
     * @param deptCode the value for sys_employee.DEPT_CODE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.CREATE_DATE
     *
     * @return the value of sys_employee.CREATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.CREATE_DATE
     *
     * @param createDate the value for sys_employee.CREATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.CREATE_USER
     *
     * @return the value of sys_employee.CREATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.CREATE_USER
     *
     * @param createUser the value for sys_employee.CREATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.UPDATE_DATE
     *
     * @return the value of sys_employee.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.UPDATE_DATE
     *
     * @param updateDate the value for sys_employee.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.UPDATE_USER
     *
     * @return the value of sys_employee.UPDATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.UPDATE_USER
     *
     * @param updateUser the value for sys_employee.UPDATE_USER
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.STATUS
     *
     * @return the value of sys_employee.STATUS
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.STATUS
     *
     * @param status the value for sys_employee.STATUS
     *
     * @mbg.generated Wed Sep 09 16:56:26 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}